// vokabeln.js

const vokabeln = [
  // PERSONALANGABEN / SZEMÉLYES ADATOK
  { deutsch: "die Adresse", ungarisch: "cím" },
  { deutsch: "das Alter", ungarisch: "életkor" },
  { deutsch: "der Beruf", ungarisch: "foglalkozás" },
  { deutsch: "die E‑Mail‑Adresse", ungarisch: "e‑mail‑cím" },
  { deutsch: "der Familienstand", ungarisch: "családi állapot" },
  { deutsch: "der Familienname", ungarisch: "vezetéknév" },
  { deutsch: "das Geburtsdatum", ungarisch: "születési idő" },
  { deutsch: "der Geburtsort", ungarisch: "születési hely" },
  { deutsch: "das Geschlecht", ungarisch: "nem" },
  { deutsch: "die Hausnummer", ungarisch: "házszám" },
  { deutsch: "die Nationalität", ungarisch: "nemzetiség" },
  { deutsch: "die Postleitzahl", ungarisch: "irányítószám" },
  { deutsch: "der Spitzname", ungarisch: "becenév" },
  { deutsch: "der Staat", ungarisch: "állam" },
  { deutsch: "die Staatsangehörigkeit", ungarisch: "állampolgárság" },
  { deutsch: "die Straße", ungarisch: "utca" },
  { deutsch: "die Telefonnummer", ungarisch: "telefonszám" },
  { deutsch: "die Unterschrift", ungarisch: "aláírás" },
  { deutsch: "der Vorname", ungarisch: "keresztnév" },
  { deutsch: "der Wohnort", ungarisch: "lakóhely" },
  { deutsch: "männlich", ungarisch: "hímnemű" },
  { deutsch: "weiblich", ungarisch: "nőnemű" },

  // FAMILIENSTAND / CSALÁDI ÁLLAPOT
  { deutsch: "alleinstehend", ungarisch: "egyedülálló" },
  { deutsch: "geschieden", ungarisch: "elvált" },
  { deutsch: "ledig", ungarisch: "hajadon" },
  { deutsch: "verheiratet", ungarisch: "házas" },
  { deutsch: "verwitwet", ungarisch: "özvegy" },

  // KÖRPERTEILE / TESTRÉSZEK
  { deutsch: "das Auge", ungarisch: "szem" },
  { deutsch: "die Augenbraue", ungarisch: "szemöldök" },
  { deutsch: "der Arm", ungarisch: "kar" },
  { deutsch: "der Bart", ungarisch: "szakáll" },
  { deutsch: "der Bauch", ungarisch: "has" },
  { deutsch: "das Bein", ungarisch: "lábszár" },
  { deutsch: "der Fuß", ungarisch: "lábfej" },
  { deutsch: "die Hand", ungarisch: "kéz" },
  { deutsch: "das Kinn", ungarisch: "áll" },
  { deutsch: "der Kopf", ungarisch: "fej" },
  { deutsch: "der Mund", ungarisch: "száj" },
  { deutsch: "die Nase", ungarisch: "orr" },
  { deutsch: "das Ohr", ungarisch: "fül" },
  { deutsch: "der Schnurrbart", ungarisch: "bajusz" },
  { deutsch: "die Stirn", ungarisch: "homlok" },
  { deutsch: "die Wange", ungarisch: "arc" },
  { deutsch: "der Zahn", ungarisch: "fog" },

  // AUSSEHEN / KÜLSŐ MEGJELENÉS
  { deutsch: "das Aussehen", ungarisch: "kinézet" },
  { deutsch: "die Farbe", ungarisch: "szín" },
  { deutsch: "die Figur", ungarisch: "alak" },
  { deutsch: "die Größe", ungarisch: "méret" },
  { deutsch: "das Haar", ungarisch: "haj" },
  { deutsch: "die Hautfarbe", ungarisch: "bőrszín" },
  { deutsch: "attraktiv", ungarisch: "vonzó" },
  { deutsch: "blass", ungarisch: "sápadt" },
  { deutsch: "blau", ungarisch: "kék" },
  { deutsch: "blond", ungarisch: "szőke" },
  { deutsch: "braun", ungarisch: "barna" },
  { deutsch: "breit", ungarisch: "széles" },
  { deutsch: "dick", ungarisch: "kövér" },
  { deutsch: "dunkel", ungarisch: "sötét" },
  { deutsch: "dünn", ungarisch: "vékony" },
  { deutsch: "faltig", ungarisch: "ráncos" },
  { deutsch: "gebräunt", ungarisch: "lebarnult" },
  { deutsch: "grau", ungarisch: "szürke" },
  { deutsch: "groß", ungarisch: "magas" },
  { deutsch: "grün", ungarisch: "zöld" },
  { deutsch: "gut aussehend", ungarisch: "jóképű" },
  { deutsch: "hell", ungarisch: "világos" },
  { deutsch: "hübsch", ungarisch: "csinos" },
  { deutsch: "jung", ungarisch: "fiatal" },
  { deutsch: "klein", ungarisch: "kicsi" },
  { deutsch: "kurz", ungarisch: "rövid" },
  { deutsch: "lang", ungarisch: "hosszú" },
  { deutsch: "lockig", ungarisch: "göndör" },
  { deutsch: "mager", ungarisch: "sovány" },
  { deutsch: "mollig", ungarisch: "molett" },
  { deutsch: "rot", ungarisch: "piros" },
  { deutsch: "rund", ungarisch: "kerek" },
  { deutsch: "schief", ungarisch: "ferde" },
  { deutsch: "schlank", ungarisch: "karcsú" },
  { deutsch: "schmal", ungarisch: "keskeny" },
  { deutsch: "schwarz", ungarisch: "fekete" },
  { deutsch: "ungepflegt", ungarisch: "ápolatlan" },
  { deutsch: "altmodisch", ungarisch: "régimódi" },
  { deutsch: "elegant", ungarisch: "elegáns" },
  { deutsch: "eng", ungarisch: "szűk" },
  { deutsch: "flach", ungarisch: "lapos" },
  { deutsch: "geschmacklos", ungarisch: "ízléstelen" },
  { deutsch: "geschmackvoll", ungarisch: "ízléses" },
  { deutsch: "klassisch", ungarisch: "klasszikus" },
  { deutsch: "modisch", ungarisch: "divatos" },
  { deutsch: "sauber", ungarisch: "tiszta" },
  { deutsch: "schick", ungarisch: "sikkes" },
  { deutsch: "schmutzig", ungarisch: "piszkos" },

  // ABKÜRZUNGEN (offizielle Formulare)
  { deutsch: "LD",     ungarisch: "hajadon" },
  { deutsch: "VH",     ungarisch: "házas" },
  { deutsch: "VW",     ungarisch: "özvegy" },
  { deutsch: "GS",     ungarisch: "elvált" }
];

// Falls du Module nutzt:
// export default vokabeln;
